name: OWASP ZAP Full Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Ejecutar DAST con OWASP ZAP
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-a'
          fail_action: false
          allow_issue_writing: true
          issue_title: 'Resultados del escaneo OWASP ZAP'
